using DraftView.Infrastructure.Parsing;

namespace DraftView.Infrastructure.Tests.Parsing;

public class ScrivenerStylesCssGeneratorTests
{
    private static IReadOnlyDictionary<int, ScrivenerStyle> ThreeStyles() =>
        new Dictionary<int, ScrivenerStyle>
        {
            [1] = new ScrivenerStyle(1, "Dialogue",         "character", "scr-style-dialogue"),
            [2] = new ScrivenerStyle(2, "Block Quote",      "paragraph", "scr-style-block-quote"),
            [3] = new ScrivenerStyle(3, "Foreign Language", "character", "scr-style-foreign-language"),
        };

    [Fact]
    public void Generate_EmptyStyles_ReturnsEmptyString()
    {
        var result = ScrivenerStylesCssGenerator.Generate(
            new Dictionary<int, ScrivenerStyle>());
        Assert.Equal(string.Empty, result);
    }

    [Fact]
    public void Generate_WithStyles_ContainsCssClassForEachStyle()
    {
        var result = ScrivenerStylesCssGenerator.Generate(ThreeStyles());

        Assert.Contains(".scr-style-dialogue",         result);
        Assert.Contains(".scr-style-block-quote",      result);
        Assert.Contains(".scr-style-foreign-language", result);
    }

    [Fact]
    public void Generate_WithStyles_ContainsAutoGeneratedComment()
    {
        var result = ScrivenerStylesCssGenerator.Generate(ThreeStyles());
        Assert.Contains("auto-generated", result);
    }

    [Fact]
    public void Generate_WithStyles_StylesAreOrderedById()
    {
        var result = ScrivenerStylesCssGenerator.Generate(ThreeStyles());

        var pos1 = result.IndexOf("scr-style-dialogue",         StringComparison.Ordinal);
        var pos2 = result.IndexOf("scr-style-block-quote",      StringComparison.Ordinal);
        var pos3 = result.IndexOf("scr-style-foreign-language", StringComparison.Ordinal);

        Assert.True(pos1 < pos2 && pos2 < pos3, "Styles should appear in ID order.");
    }

    [Fact]
    public void Generate_CharacterStyle_ContainsProsePrefixedSelector()
    {
        var result = ScrivenerStylesCssGenerator.Generate(ThreeStyles());
        Assert.Contains(".prose .scr-style-dialogue", result);
    }

    [Fact]
    public void Generate_ParagraphStyle_ContainsProsePrefixedSelector()
    {
        var result = ScrivenerStylesCssGenerator.Generate(ThreeStyles());
        Assert.Contains(".prose .scr-style-block-quote", result);
    }
}
